version: '3'
services:
  web:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - db
    image: kommunar/va1
  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    image: kommunar/va2

